### ISSUE TITLE
JavaScript exception in new ARM Build

### ISSUE THREAD

**Issue by gaithoben** [arangodb/oskar#494]
2023-02-22T09:19:15Z [8149] WARNING [0458b] {general} 🥑 This is a maintainer version intended for debugging. DO NOT USE IN PRODUCTION! 🔥
2023-02-22T09:19:15Z [8149] WARNING [bd666] {general} ===================================================================================
2023-02-22T09:19:15Z [8149] INFO [75ddc] {general} detected operating system: macos
2023-02-22T09:19:15Z [8149] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is unlimited, soft limit is 10240
2023-02-22T09:19:15Z [8149] INFO [3bb7d] {cluster} Starting up with role SINGLE
2023-02-22T09:19:16Z [8149] INFO [fe333] {engines} RocksDB recovery starting, scanning WAL starting from sequence number 0, latest sequence number: 3, files in archive: 0
2023-02-22T09:19:16Z [8149] INFO [a4ec8] {engines} RocksDB recovery finished, WAL entries scanned: 4, recovery start sequence number: 0, latest WAL sequence number: 3, max tick value found in WAL: 1, last HLC value found in WAL: 0
2023-02-22T09:19:16Z [8149] ERROR [8a210] {general} JavaScript exception in file '/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js' at 561,9: ArangoError 3103: failed to invoke module\nFile: /Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/js/server/modules/@arangodb/index.js\nReason: ArangoError: cannot locate module\nFile: semver\n    at Function.Module._resolveFilename (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:530:13)\n    at Function.Module._load (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:449:27)\n    at require (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:98:21)\n    at Object.<anonymous> (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/js/server/modules/@arangodb/index.js:29:16)\n    at Module._compile (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:604:8)\n    at Object.Module._extensions..js (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:622:12)\n    at Module.load (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:549:36)\n    at Function.Module._load (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:494:16)\n    at global.require (/Users/bernardgaitho/@arangodb/oskar3.10.2/work/ArangoDB/./js/common/bootstrap/modules.js:643:19)\n    at server/initialize.js:65:19
2023-02-22T09:19:16Z [8149] ERROR [409ee] {general} !        throw Object.assign(
2023-02-22T09:19:16Z [8149] ERROR [cb0bd] {general} !        ^
2023-02-22T09:19:16Z [8149] FATAL [69ac3] {v8} error during execution of JavaScript file 'server/initialize.js'

**Comment by gaithoben** [comment]
Once i build arangodb with M2 Mac, i am getting above error. Your help will be appreciated.

**Comment by dothebart** [comment]
hm, which config did you specify? there should be `js/node/node_modules/semver`. 
Try launching:
`./build/bin/arangod -c etc/relative/arangod.conf somedatabasedirectory`
from oskar/work/ArangoDB

**Comment by gaithoben** [comment]
I was able to soft the issue be deleting the ArangoDB folder and then calling afresh ‘ checkoutArangoDB’ 

thanks alot for your help. I appreciate alot.
